apiVersion: v1
kind: ConfigMap
metadata:
  name: youtube-streams-config
  namespace: youtube-to-rtsp
data:
  # Format: "stream_namn: youtube_url"
  NSF: "https://www.youtube.com/watch?v=mhJRzQsLZGg"
  Avid-R1: "https://www.youtube.com/watch?v=inCQ49QGmqQ"
  Avid-R2: "https://www.youtube.com/watch?v=tS2PHJmvJzo"
  Avid-R3: "https://www.youtube.com/watch?v=TyXUaqscyiU"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediamtx
  namespace: youtube-to-rtsp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediamtx
  template:
    metadata:
      labels:
        app: mediamtx
    spec:
      containers:
      - name: mediamtx
        image: bluenviron/mediamtx:latest
        ports:
        - containerPort: 8554 # RTSP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-multi-streamer
  namespace: youtube-to-rtsp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-streamer
  template:
    metadata:
      labels:
        app: multi-streamer
    spec:
      containers:
      - name: streamer
        image: alpine:latest
        ports:
          - containerPort: 8554
            name: youtube-to-rtsp
            protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /etc/streams
        command: ["/bin/sh", "-c"]
        args:
          - |
            apk add --no-cache ffmpeg yt-dlp;
            
            # Skript som loopar igenom alla konfigurerade strömmar
            for stream_file in /etc/streams/*; do
              stream_name=$(basename $stream_file)
              stream_url=$(cat $stream_file)
              
              echo "Startar worker för: $stream_name"
              
              # Kör varje stream i bakgrunden i en oändlig loop
              (
                while true; do
                  REAL_URL=$(yt-dlp -g -f 'best[vcodec^=avc1]' "$stream_url")
                  ffmpeg -re -i "$REAL_URL" -c copy -f rtsp "rtsp://mediamtx-service:8554/$stream_name"
                  echo "Ström $stream_name dog, startar om..."
                  sleep 10
                done
              ) &
            done
            
            # Håll containern vid liv
            wait
      volumes:
      - name: config-volume
        configMap:
          name: youtube-streams-config
---
apiVersion: v1
kind: Service
metadata:
  name: youtube-to-rtsp
  namespace: youtube-to-rtsp
spec:
  allocateLoadBalancerNodePorts: true
  ports:
  - name: youtube-to-rtsp
    port: 8554
    protocol: TCP
    targetPort: mediamtx
  selector:
    app: mediamtx
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 192.168.0.79
