apiVersion: v1
kind: PersistentVolume
metadata:
  name: omada-data-pv
  namespace: omada
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/omada/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: omada-logs-pv
  namespace: omada
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/omada/logs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omada-data-pvc
  namespace: omada
spec:
  storageClassName: local-path
  volumeName: omada-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omada-logs-pvc
  namespace: omada
spec:
  storageClassName: local-path
  volumeName: omada-logs-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: omada
  name: omada-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: omada-controller
  template:
    metadata:
      labels:
        app: omada-controller
    spec:
      securityContext:
        runAsUser: 508
        runAsGroup: 508
        runAsNonRoot: true
        fsGroup: 508
        fsGroupChangePolicy: "OnRootMismatch"
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: omada-controller
        image: mbentley/omada-controller:6.1
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        env:
        - name: ROOTLESS
          value: "true"
        - name: MANAGE_HTTP_PORT
          value: "8088"
        - name: MANAGE_HTTPS_PORT
          value: "8043"
        - name: PORTAL_HTTP_PORT
          value: "8088"
        - name: PORTAL_HTTPS_PORT
          value: "8843"
        - name: UPGRADE_HTTPS_PORT
          value: "8043"
        - name: PORT_APP_DISCOVERY
          value: "27001"
        - name: PORT_ADOPT_V1
          value: "29812"
        - name: PORT_UPGRADE_V1
          value: "29813"
        - name: PORT_MANAGER_V1
          value: "29811"
        - name: PORT_MANAGER_V2
          value: "29814"
        - name: PORT_DISCOVERY
          value: "29810"
        - name: PORT_TRANSFER_V2
          value: "29815"
        - name: PORT_RTTY
          value: "29816"
        - name: PORT_DEVICE_MONITOR
          value: "29817"
        - name: SHOW_SERVER_LOGS
          value: "true"
        - name: SHOW_MONGODB_LOGS
          value: "false"
        - name: SSL_CERT_NAME
          value: tls.crt
        - name: SSL_KEY_NAME
          value: tls.key
        - name: TZ
          value: Etc/UTC
        - name: SKIP_USERMOD
          value: "true"
        volumeMounts:
        - name: omada-data
          mountPath: /opt/tplink/EAPController/data
        - name: omada-logs
          mountPath: /opt/tplink/EAPController/logs
      volumes:
      - name: omada-data
        persistentVolumeClaim:
          claimName: omada-data-pvc
      - name: omada-logs
        persistentVolumeClaim:
          claimName: omada-logs-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: omada-svc
  namespace: omada
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.78
  selector:
    app: omada-controller
  ports:
  - name: manage-http
    port: 8088
    targetPort: 8088
    protocol: TCP
  - name: manage-https
    port: 8043
    targetPort: 8043
    protocol: TCP
  - name: portal-https
    port: 8843
    targetPort: 8843
    protocol: TCP
  - name: app-discovery
    port: 27001
    targetPort: 27001
    protocol: UDP
  - name: adopt-v1
    port: 29812
    targetPort: 29812
    protocol: TCP
  - name: upgrade-v1
    port: 29813
    targetPort: 29813
    protocol: TCP
  - name: manager-v1
    port: 29811
    targetPort: 29811
    protocol: TCP
  - name: manager-v2
    port: 29814
    targetPort: 29814
    protocol: TCP
  - name: udp-discovery
    port: 29810
    targetPort: 29810
    protocol: UDP
  - name: udp-management
    protocol: UDP
    port: 19810
    targetPort: 19810
  - name: transfer-v2
    port: 29815
    targetPort: 29815
    protocol: TCP
  - name: rtty
    port: 29816
    targetPort: 29816
    protocol: TCP
  - name: device-monitor
    port: 29817
    targetPort: 29817
    protocol: TCP

