apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docmost
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/docmost/charts'
      chart: docmost
      targetRevision: 0.1.3
    - repoURL: "https://github.com/joakimberglund/home-setup.git"
      targetRevision: main
      path: "kubernetes/components/docmost"
  destination:
    server: https://kubernetes.default.svc
    namespace: docmost
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
