apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apploader
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/joakimberglund/home-setup'
    targetRevision: main
    path: kubernetes/apps
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated: { prune: true, selfHeal: true }