apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smhi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/joakimberglund/SMHI-forecast-to-InfluxDBv1.git"
    targetRevision: main
    path: "/"
  destination:
    server: https://kubernetes.default.svc
    namespace: smhi
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
